### ISSUE TITLE
How to use ARKitStreamer with AR Foundation 4.0.0-preview.3

### ISSUE THREAD

**Issue by makihiro** [asus4/ARKitStreamer#13]
Hello. I would like to use ARKitStreamer with AR Foundation 4.0.0-preview.3.
There are some errors when I trying to run.

``
No active UnityEngine.XR.ARSubsystems.XRCameraSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
UnityEngine.XR.ARFoundation.SubsystemLifecycleManager`2:OnEnable() (at Library/PackageCache/com.unity.xr.arfoundation@4.0.0-preview.3/Runtime/AR/SubsystemLifecycleManager.cs:66)
``
I think it is related to XRLoader which loads subsystems while SubsystemManager.GetInstances is used in 4.0.0-preview.1.
It would be helpful if there is some way to fix an error.
Thanks,

**Comment by asus4** [comment]
Hi @makihiro, Sorry for the late reply. Updated AR libraries version to 4.1.3, Unity version to 2020.2.1f1. Hope it helps!
