### ISSUE TITLE
token is expired

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [asus4/ARKitStreamer#20]
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.unity.toolchain.macos-x86_64-linux-x86_64: Cannot fetch authorization code. User access token is expired or invalid. You may need to sign out and sign in again.
  Package com.unity.toolchain.macos-x86_64-linux-x86_64@0.1.22-preview has invalid dependencies or related test packages:
    com.unity.sysroot (dependency): Cannot fetch authorization code. User access token is expired or invalid. You may need to sign out and sign in again.
    com.unity.sysroot.linux-x86_64 (dependency): Cannot fetch authorization code. User access token is expired or invalid. You may need to sign out and sign in again.

A re-import of the project may be required to fix the issue or a manual modification of C:/Users/Jose/Documents/Projetos/ARKitStreamer/Packages/manifest.json file.

**Comment by asus4** [comment]
@GCPBigData thanks for reporting. I removed the toolchain `com.unity.toolchain.macos-x86_64-linux-x86_64` from dependency as it is not required. This should fix the issue. 

BTW are you testing it on Windows? I have tested it on macOS. So you might get errors on Windows. PRs are welcome. Thanks.
