### ISSUE TITLE
Problem with game view in Unity

### ISSUE THREAD

**Issue by Oneiros90** [asus4/ARKitStreamer#23]
Hi, this is what I see after building the app on my iPhone XS and running it both in editor and on device.
The connection is clearly correctly established but the image is rotated by 90 degrees and there are chromatic problems. Any idea how to correct this issue? Thanks

![immagine](https://user-images.githubusercontent.com/2072766/212339159-f228134a-cac1-448b-b2e2-14a09e7a6b0d.png)

**Comment by gblikas** [comment]
@Oneiros90 I thought I had a similar problem on my end, but after restarting the app while the editor was continuing to run I got a successful compilied image (attached) 
<img width="1532" alt="Screenshot 2023-06-11 at 3 53 27 PM" src="https://github.com/asus4/ARKitStreamer/assets/13577108/cf6d99ff-4a3a-49a4-8e2e-16519d7cface">
