### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by bilck** [asus4/ARKitStreamer#3]
So, I have installed the NDI SDK for iOS and macOS, but I play some sample scenes and nothing happens (my iPhone X is connected using USB).

I suppose I have to install some app on the iPhone as well, right? But which one?

**Comment by asus4** [comment]
@bilck Hi, I just added more instructions to README

**Comment by bilck** [comment]
Thanks a lot, I'll try that as soon as possible!

**Comment by bilck** [comment]
@asus4 So, I have successfully compiled the project, just had some issue to add the NDI Library to XCode (not used to XCode, I believe you could explain that on your documentation).

The problem is that I had managed to run the project on iOS (and recognized my face) but I wasn't able to reproduce the Face Mesh on the editor.
I was able to find my phone on NdiReceiver class in Unity Editor, but nothing more than that:
![image](https://user-images.githubusercontent.com/339639/68701875-75d64080-0566-11ea-95e2-2d60ab882529.png)

**Comment by asus4** [comment]
Thanks for testing!

1. Please check iPhone's IP address, with ping command `ping 172.20.10.1`
2. If UnityEditor throws errors in NativeArray.cs 
 -> https://github.com/asus4/ARKitStreamer/issues/2#issuecomment-552880905

**Comment by bilck** [comment]
Ok, so I managed to make it work. I was obviously pointing to the wrong IP (I know it's kind obvious, but that could be added to usage instructions).

As a side-note it's also important to mention to set IP and point to the proper source name **before** playing the scene.

Just one issue, the background camera didn't appear:
![image](https://user-images.githubusercontent.com/339639/68792311-e003e980-0629-11ea-9255-1debf4697ca0.png)

Is that expected?

One more last question: how to make it properly work through USB connection?

Thanks a lot!

**Comment by asus4** [comment]
@bilck  Please check the NDI Source name is correct. or you might have to restart the iOS sender app.


## iPhone USB network

- Enable Personal Hotspot setting on your iPhone.
- In the case of your Mac and iPhone are connected to the same Wi-Fi, turn off Wi-Fi network. Since mac preferred to use the Wi-Fi network.

![Screen Shot 2019-11-14 at 10 08 56](https://user-images.githubusercontent.com/357497/68842518-ca90cd00-06c6-11ea-81b6-93cbe9bce200.png)

**Comment by bilck** [comment]
For some reason it's still not working:
![image](https://user-images.githubusercontent.com/339639/69179974-38842c80-0aeb-11ea-9ead-f667a37891de.png)

Seems to be something related to texture format or material/shader.

**Comment by bilck** [comment]
So, any news about that?

**Comment by asus4** [comment]
I could not reproduce it. it seems the NDI related problem. Could you try if sending NDI from iPhone to Mac is possible?

**Comment by bilck** [comment]
So, I have installed NDI Monitor on my Mac (https://apps.apple.com/us/app/ndi-monitor/id1111704079?mt=12) but it didn't work out. Check image below:
![image](https://user-images.githubusercontent.com/339639/69830677-a96ec700-1204-11ea-9765-e6a7bf1d068b.png)

**Comment by asus4** [comment]
1. Does your iPhone X throw any errors on Xcode?
2. Can you try another NDI sender app to break down the issue.
https://apps.apple.com/us/app/ndikun/id1473541220

**Comment by QuestionsBrown** [comment]
> @asus4 So, I have successfully compiled the project, just had some issue to add the NDI Library to XCode (not used to XCode, I believe you could explain that on your documentation).
> 
> The problem is that I had managed to run the project on iOS (and recognized my face) but I wasn't able to reproduce the Face Mesh on the editor.
> I was able to find my phone on NdiReceiver class in Unity Editor, but nothing more than that:
> ![image](https://user-images.githubusercontent.com/339639/68701875-75d64080-0566-11ea-95e2-2d60ab882529.png)

If either of you could help me get rid of this same compile error while trying to build in Xcode using the manual plugin insert strategy you guys suggest here that would make my day! <3

- Q
