### ISSUE TITLE
Changing the Manifest file results in compile errors (Unity 2019.3.4)

### ISSUE THREAD

**Issue by klauskobald** [asus4/ARKitStreamer#8]
Library/PackageCache/com.koki-ibukuro.arkitstream@0.2.2/Runtime/Internal/Subsystems/ARKitRemotePoseProvider.cs(11,39): error CS0115: 'ARKitRemotePoseProvider.GetPoseFromProvider(out Pose)': no suitable method found to override
Library/PackageCache/com.koki-ibukuro.arkitstream@0.2.2/Runtime/Internal/Subsystems/ARKitRemotePoseProvider.cs(9,18): error CS0534: 'ARKitRemotePoseProvider' does not implement inherited abstract member 'BasePoseProvider.TryGetPoseFromProvider(out Pose)'
Library/PackageCache/com.koki-ibukuro.arkitstream@0.2.2/Runtime/Senders/ARKitOcclusionSender.cs(9,26): error CS0246: The type or namespace name 'AROcclusionManager' could not be found (are you missing a using directive or an assembly reference?)

**Comment by asus4** [comment]
@klauskobald Cloud you make a minimum project to reproduce this error?
